### ISSUE TITLE
Compiler error on passing lamda to messageRouterRegister method

### ISSUE THREAD

**Issue by siakc** [Spiek/telegrambotlib-qt#1]
```
bot.messageRouterRegister("/start",
        [&bot](TelegramBotUpdate update)
        {
           bot.sendMessage(update->message->chat.id, "Hi, I'am a Test bot");
           return true;
        }
    , TelegramBotMessageType::Message);

```
Generates error in kit: Desktop Qt 5.10.0 MSVC2017 64bit as follows:

> error C2664: 'void TelegramBot::messageRouterRegister(QString,QDelegate<bool (TelegramBotUpdate)>,TelegramBotMessageType)': cannot convert argument 2 from 'main::<lambda_3be0076418be40d7d525cf0ed23bc3b0>' to 'QDelegate<bool (TelegramBotUpdate)>'

**Comment by Spiek** [comment]
thanks for your issue :-)
It was a mistake in the example, it's now fixed in: https://github.com/Spiek/telegrambotlib-qt/commit/aeaced772c46cf392fad5f9cb12b09cf73d65ec3

correct syntax is:
```
bot.messageRouterRegister("/start", {[&bot](TelegramBotUpdate update)
        {
           bot.sendMessage(update->message->chat.id, "Hi, I'am a Test bot");
           return true;
        }
    }, TelegramBotMessageType::Message);
```
