### ISSUE TITLE
QEventLoop: Cannot be used without QApplication

### ISSUE THREAD

**Issue by siakc** [Spiek/telegrambotlib-qt#2]
When we run this example in Windows 7:
```
#include <telegrambotlib-qt/telegrambot.h>
#include <QCoreApplication>


int main(int argc, char *argv[])
{
    QCoreApplication a(argc, argv);

    TelegramBot bot("340163358:AAEV0eghLuzpkTO7FcylhPeYtaCF8i6YTok");
    bot.messageRouterRegister("/start",
        {[&bot](TelegramBotUpdate update)
        {
           bot.sendMessage(update->message->chat.id, "Hi, I'am a Test bot");
           return true;
        }}
    , TelegramBotMessageType::Message);

    bot.startMessagePulling();




    return a.exec();
}
```

After SSL connection in console window I get the title message and application hangs.

**Comment by Spiek** [comment]
Your code works just fine in my environment (Windows 10; mingw Qt5.9)

Qt is loading the ssl library by run time.. so i think you need them.

you can install them the following way (src: https://wiki.openssl.org/index.php/Binaries):

1. Download them here: https://indy.fulgan.com/SSL/  (i use mingw as compiler so i have to choose the 32-bit one!)
2. Put the two dll's (libeay32.dll and ssleay32.dll) into your qt directory: C:\Qt\5.9.2\mingw53_32\bin
3. recompile and rerun the application, if qt has loaded the library correctly the warnings should disappear

**Comment by Spiek** [comment]
could my answer help you to solve your problem? or is it still present? :-)
if you have still an issue, could you post the output of the application here?
